// Generated by https://jvilk.com/MakeTypes/

export interface WeatherForecast {
  current_condition?: (CurrentConditionEntity)[] | null;
  nearest_area?: (NearestAreaEntity)[] | null;
  request?: (RequestEntity)[] | null;
  weather?: (WeatherEntity)[] | null;
}
export interface CurrentConditionEntity {
  FeelsLikeC: string;
  FeelsLikeF: string;
  cloudcover: string;
  humidity: string;
  localObsDateTime: string;
  observation_time: string;
  precipInches: string;
  precipMM: string;
  pressure: string;
  pressureInches: string;
  temp_C: string;
  temp_F: string;
  uvIndex: string;
  visibility: string;
  visibilityMiles: string;
  weatherCode: string;
  weatherDesc?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  weatherIconUrl?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  winddir16Point: string;
  winddirDegree: string;
  windspeedKmph: string;
  windspeedMiles: string;
}
export interface WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity {
  value: string;
}
export interface NearestAreaEntity {
  areaName?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  country?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  latitude: string;
  longitude: string;
  population: string;
  region?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  weatherUrl?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
}
export interface RequestEntity {
  query: string;
  type: string;
}
export interface WeatherEntity {
  astronomy?: (AstronomyEntity)[] | null;
  avgtempC: string;
  avgtempF: string;
  date: string;
  hourly?: (HourlyEntity)[] | null;
  maxtempC: string;
  maxtempF: string;
  mintempC: string;
  mintempF: string;
  sunHour: string;
  totalSnow_cm: string;
  uvIndex: string;
}
export interface AstronomyEntity {
  moon_illumination: string;
  moon_phase: string;
  moonrise: string;
  moonset: string;
  sunrise: string;
  sunset: string;
}
export interface HourlyEntity {
  DewPointC: string;
  DewPointF: string;
  FeelsLikeC: string;
  FeelsLikeF: string;
  HeatIndexC: string;
  HeatIndexF: string;
  WindChillC: string;
  WindChillF: string;
  WindGustKmph: string;
  WindGustMiles: string;
  chanceoffog: string;
  chanceoffrost: string;
  chanceofhightemp: string;
  chanceofovercast: string;
  chanceofrain: string;
  chanceofremdry: string;
  chanceofsnow: string;
  chanceofsunshine: string;
  chanceofthunder: string;
  chanceofwindy: string;
  cloudcover: string;
  humidity: string;
  precipInches: string;
  precipMM: string;
  pressure: string;
  pressureInches: string;
  tempC: string;
  tempF: string;
  time: string;
  uvIndex: string;
  visibility: string;
  visibilityMiles: string;
  weatherCode: string;
  weatherDesc?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  weatherIconUrl?: (WeatherDescEntityOrWeatherIconUrlEntityOrAreaNameEntityOrCountryEntityOrRegionEntityOrWeatherUrlEntity)[] | null;
  winddir16Point: string;
  winddirDegree: string;
  windspeedKmph: string;
  windspeedMiles: string;
}
